import torch
import numpy as np

def prepare_subject_experiment_by_tokens(file_path, subject_idx=0, n_history_tokens=1500):
    """
    Prepares simulation data based on a fixed number of history tokens.
    Everything after n_history_tokens is split into Menu (food) and Truth (glucose).
    """
    # 1. Load the split file (which contains only 'tokens')
    data = torch.load(file_path, weights_only=False)
    
    # Extract tokens for the selected subject
    # Based on your split script, 'data' is a dict with 'tokens' key
    all_subject_tokens = data['tokens'][subject_idx]
    
    # Convert to list and remove padding (zeros)
    tokens = [int(t) for t in all_subject_tokens if t > 0]
    
    # 2. Split into History and Future
    if len(tokens) <= n_history_tokens:
        print(f"Warning: Subject only has {len(tokens)} tokens. Reducing history.")
        n_history_tokens = len(tokens) // 2
        
    history_tokens = tokens[:n_history_tokens]
    future_tokens = tokens[n_history_tokens:]
    
    # 3. Separate Future tokens into Menu and Ground Truth
    # Rule: Token <= 500 is Glucose, Token > 500 is Nutrient
    menu_per_step = {}
    true_glucose = []
    
    current_time_step = 0
    for t in future_tokens:
        if t <= 461:
            # It's a glucose measurement (marks a new 15-min interval)
            true_glucose.append(t)
            current_time_step += 1
        else:
            # It's a food token belonging to the current/next step
            # We map it to the current_time_step index
            step_idx = max(0, current_time_step - 1)
            if step_idx not in menu_per_step:
                menu_per_step[step_idx] = []
            menu_per_step[step_idx].append(t)
            
    return {
        'history': history_tokens,
        'menu': menu_per_step,
        'truth': true_glucose,
        'n_history': len(history_tokens),
        'n_forecast_steps': len(true_glucose)
    }

def display_data_report(exp_data):
    """
    Prints a detailed report of the prepared data.
    """
    print(f"\n{'#'*60}")
    print(f" EXPERIMENT DATA REPORT ")
    print(f"{'#'*60}")
    print(f"Total History Tokens: {exp_data['n_history']}")
    print(f"First 10 tokens: {exp_data['history'][:10]}")
    
    glucose_in_hist = sum(1 for t in exp_data['history'] if t <= 500)
    food_in_hist = exp_data['n_history'] - glucose_in_hist
    print(f"  -> Glucose steps in history: {glucose_in_hist}")
    print(f"  -> Food tokens in history: {food_in_hist}")
    
    print(f"\nForecast Window:")
    print(f"  -> Total 15-min steps to predict: {exp_data['n_forecast_steps']}")
    print(f"  -> Total meals to inject: {len(exp_data['menu'])}")
    
    # Show first 3 meals
    if exp_data['menu']:
        print("\nFirst 3 meals in menu:")
        for i, (step, m_tokens) in enumerate(sorted(exp_data['menu'].items())):
            if i >= 3: break
            print(f"  Step {step}: Tokens {m_tokens}")
            
    print(f"{'#'*60}\n")

if __name__ == "__main__":
    # Path to the file generated by your split script
    VAL_FILE = 'val_cgmacros_split.pt' 
    
    # Parameter: how many tokens to use as context
    N_HISTORY = 2000 
    
    experiment = prepare_subject_experiment_by_tokens(VAL_FILE, subject_idx=2, n_history_tokens=N_HISTORY)
    display_data_report(experiment)
    
    # Save for the prediction script
    torch.save(experiment, 'simulation_input.pt')
    print("✅ Data ready and saved to 'simulation_input.pt'")